version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    restart: always
    volumes:
      - .:/app
    command: ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "app:app"]
